export default () => ({
  BASE_SEARCH_URL: process.env.BASE_SEARCH_URL,
  BASE_RECOMMENDATION_URL: process.env.BASE_RECOMMENDATION_URL,
  SPOTIFY_GRANT_TYPE: process.env.SPOTIFY_GRANT_TYPE,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
  SPOTIFY_GET_TOKEN_URL: process.env.SPOTIFY_GET_TOKEN_URL,
});
